package ru.tech.averagemark.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF5b6400)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFdeed1d)
val md_theme_light_onPrimaryContainer = Color(0xFF1a1e00)
val md_theme_light_secondary = Color(0xFF5e6043)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe4e5c0)
val md_theme_light_onSecondaryContainer = Color(0xFF1b1d06)
val md_theme_light_tertiary = Color(0xFF3b6659)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbeeddc)
val md_theme_light_onTertiaryContainer = Color(0xFF002019)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFFCFCE1)
val md_theme_light_onBackground = Color(0xFF242407)
val md_theme_light_surface = Color(0xFFfffcf3)
val md_theme_light_onSurface = Color(0xFF1c1c17)
val md_theme_light_surfaceVariant = Color(0xFFe5e3d2)
val md_theme_light_onSurfaceVariant = Color(0xFF47473b)
val md_theme_light_outline = Color(0xFF787869)
val md_theme_light_inverseOnSurface = Color(0xFFf4f1e8)
val md_theme_light_inverseSurface = Color(0xFF31312b)
val md_theme_light_inversePrimary = Color(0xFFc2d000)

val md_theme_dark_primary = Color(0xFFc2d000)
val md_theme_dark_onPrimary = Color(0xFF2e3300)
val md_theme_dark_primaryContainer = Color(0xFF444b00)
val md_theme_dark_onPrimaryContainer = Color(0xFFdeed1d)
val md_theme_dark_secondary = Color(0xFFc8c9a6)
val md_theme_dark_onSecondary = Color(0xFF303219)
val md_theme_dark_secondaryContainer = Color(0xFF47492e)
val md_theme_dark_onSecondaryContainer = Color(0xFFe4e5c0)
val md_theme_dark_tertiary = Color(0xFFa2d0c0)
val md_theme_dark_onTertiary = Color(0xFF07372c)
val md_theme_dark_tertiaryContainer = Color(0xFF234e42)
val md_theme_dark_onTertiaryContainer = Color(0xFFbeeddc)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1B1B04)
val md_theme_dark_onBackground = Color(0xFFCECAA7)
val md_theme_dark_surface = Color(0xFF1c1c17)
val md_theme_dark_onSurface = Color(0xFFe5e2da)
val md_theme_dark_surfaceVariant = Color(0xFF47473b)
val md_theme_dark_onSurfaceVariant = Color(0xFFc8c7b7)
val md_theme_dark_outline = Color(0xFF929182)
val md_theme_dark_inverseOnSurface = Color(0xFF1c1c17)
val md_theme_dark_inverseSurface = Color(0xFFe5e2da)
val md_theme_dark_inversePrimary = Color(0xFF5b6400)


val color_0 = Color.DarkGray
val color_2 = Color(0xFFE53935)
val color_3 = Color(0xFFFB8C00)
val color_4 = Color(0xFF7CB342)
val color_5 = Color(0xFF8E24AA)